full_name = input("Enter your full name: ")
address = input("Enter your address: ")
contact = input("Enter your contact number: ")
email = input("Enter your email address: ")
print("\n--- User Details ---")
print(f"Full Name: {full_name}")
print(f"Address: {address}")
print(f"Contact Number: {contact}")
print(f"Email: {email}")
